version: '3'
services:
  app:
    build: .
    container_name: p2p-server
    hostname: p2p-server-hostname
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/p2p-db
  db:
    image: mongo
    container_name: p2p-database
    hostname: p2p-database-hostname
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5